# ============================================
# 📱 WECHAT CLONE - FLUTTER PROJECT
# ============================================
# Name des Projekts - wie deine App heißt
name: wechat_clone_new

# Beschreibung - was macht deine App?
description: "Ein professionelles WeChat Clone mit MVVM Architektur"

# Verhindert versehentliches Veröffentlichen
publish_to: 'none'

# ============================================
# 🔢 VERSION MANAGEMENT
# ============================================
# Version Format: MAJOR.MINOR.PATCH+BUILD
# 1.0.0+1 bedeutet:
#   - 1 = Haupt-Version (große Änderungen)
#   - 0 = Minor-Version (neue Features)
#   - 0 = Patch-Version (Bugfixes)
#   - +1 = Build-Nummer
version: 1.0.0+1

# ============================================
# 🎯 DART SDK VERSION
# ============================================
# Welche Dart Version brauchen wir?
# ^3.9.2 = Version 3.9.2 oder höher (aber unter 4.0.0)
environment:
  sdk: ^3.9.2

# ============================================
# 📦 DEPENDENCIES (Pakete die wir brauchen)
# ============================================
dependencies:
  # ⚡ FLUTTER CORE (Das wichtigste Paket!)
  flutter:
    sdk: flutter
  
  # ============================================
  # 🧠 STATE MANAGEMENT (Zustandsverwaltung)
  # ============================================
  # Provider = Wie wir Daten zwischen Screens teilen
  # MVVM braucht das! ViewModel kommuniziert mit View
  provider: ^6.1.1
  
  # ============================================
  # 🌐 NETWORKING (Internet-Kommunikation)
  # ============================================
  # HTTP = Einfache API Calls (GET, POST, etc.)
  http: ^1.1.0
  
  # Dio = Fortgeschrittene HTTP Requests
  # Besser als http, mit Interceptors, Timeouts, etc.
  dio: ^5.3.2
  
  # ============================================
  # 💬 REAL-TIME COMMUNICATION (Echtzeit-Chat)
  # ============================================
  # Socket.IO = Websockets für Echtzeit-Nachrichten
  # Damit können 2 User gleichzeitig chatten
  socket_io_client: ^2.0.3+1
  
  # Agora = Video/Audio Anrufe
  # Wie Zoom oder WhatsApp Calls
  agora_rtc_engine: ^6.3.2
  
  # WebRTC = Peer-to-Peer Video Calls
  # Alternative zu Agora, direkte Verbindung
  flutter_webrtc: ^0.11.7
  
  # ============================================
  # 💾 LOCAL STORAGE (Lokale Datenspeicherung)
  # ============================================
  # SharedPreferences = Kleine Daten speichern
  # z.B. User-Einstellungen, Login-Status
  shared_preferences: ^2.2.2
  
  # Path Provider = Dateipfade finden
  # z.B. wo speichern wir Bilder auf dem Gerät?
  path_provider: ^2.1.1
  
  # Path = Dateipfad-Operationen
  # z.B. Pfad kombinieren, Dateiname extrahieren
  path: ^1.8.3
  
  # ============================================
  # 🖼️ IMAGE HANDLING (Bilder)
  # ============================================
  # Cached Network Image = Bilder aus Internet laden + cachen
  # Lädt Bild einmal, speichert es lokal für später
  cached_network_image: ^3.3.0
  
  # Image Picker = Bilder wählen (Kamera oder Galerie)
  # User kann Profilbild hochladen
  image_picker: ^1.0.4
  
  # Image = Bild-Bearbeitung (resize, crop, etc.)
  image: ^4.1.3
  
  # Camera = Zugriff auf Kamera
  # Für Stories, Video-Posts, etc.
  camera: ^0.10.5
  
  # ============================================
  # 🎬 VIDEO FEATURES (Video)
  # ============================================
  # Video Player = Videos abspielen
  video_player: ^2.8.1
  
  # Chewie = Besserer Video Player mit Controls
  # Play/Pause Buttons, Fortschrittsbalken, etc.
  chewie: ^1.7.4
  
  # Video Thumbnail = Vorschaubild aus Video erstellen
  video_thumbnail: ^0.5.3
  
  # ============================================
  # 🎵 AUDIO FEATURES (Audio)
  # ============================================
  # Audio Players = Audio abspielen
  audioplayers: ^5.2.1
  
  # Audio Waveforms = Wellenform-Anzeige für Sprachnachrichten
  # Zeigt visuelle Wellen wie bei WhatsApp Voice Messages
  audio_waveforms: ^1.0.5
  
  # Record = Audio aufnehmen
  # Für Sprachnachrichten
  record: ^6.1.0
  
  # ============================================
  # 🔥 FIREBASE (Backend as a Service)
  # ============================================
  # Firebase Core = Basis-Paket (MUSS immer dabei sein!)
  firebase_core: ^3.6.0
  
  # Cloud Firestore = NoSQL Datenbank
  # Hier speichern wir User, Messages, Posts, etc.
  cloud_firestore: ^5.4.4
  
  # Firebase Storage = Datei-Upload
  # Bilder, Videos, Dokumente hochladen
  firebase_storage: ^12.3.4
  
  # Firebase Auth = User-Authentifizierung
  # Login, Register, Passwort vergessen
  firebase_auth: ^5.3.1
  
  # Firebase Messaging = Push Notifications
  # "Du hast eine neue Nachricht!" Benachrichtigungen
  firebase_messaging: ^15.1.3
  
  # ============================================
  # 🔐 AUTHENTICATION PROVIDERS (Login-Methoden)
  # ============================================
  # Google Sign In = "Mit Google anmelden"
  google_sign_in: ^6.2.1
  
  # Sign In With Apple = "Mit Apple anmelden"
  # Pflicht für iOS Apps!
  sign_in_with_apple: ^6.1.0
  
  # Crypto = Verschlüsselung
  # Für sichere Passwort-Hashing
  crypto: ^3.0.3
  
  # ============================================
  # 💳 PAYMENT (Bezahlung)
  # ============================================
  # Flutter Stripe = Kreditkarten-Zahlungen
  # Für E-Commerce Features
  flutter_stripe: ^11.3.0
  
  # ============================================
  # 📍 LOCATION (Standort)
  # ============================================
  # Geolocator = GPS Position bekommen
  # Für Dating-Feature: "User in der Nähe finden"
  geolocator: ^10.1.0
  
  # ============================================
  # 🎮 GAMING (Spiele-Features)
  # ============================================
  # Flame = 2D Game Engine für Flutter
  # Für Mini-Games wie in WeChat
  flame: ^1.15.0
  
  # ============================================
  # 🎨 UI COMPONENTS (Benutzeroberfläche)
  # ============================================
  # Flutter Staggered Animations = Sequenzielle Animationen
  # Elemente erscheinen nacheinander (schöner Effekt!)
  flutter_staggered_animations: ^1.1.1
  
  # Shimmer = Lade-Effekt (wie bei Facebook)
  # Grauer "loading skeleton" während Daten laden
  shimmer: ^3.0.0
  
  # Infinite Scroll Pagination = Unendliches Scrollen
  # Wie Instagram/TikTok Feed
  infinite_scroll_pagination: ^4.0.0
  
  # Staggered Grid View = Pinterest-Style Grid
  # Bilder in unterschiedlichen Größen anzeigen
  flutter_staggered_grid_view: ^0.7.0
  
  # Carousel Slider = Slideshow
  # Bilder durchwischen (wie Instagram Stories)
  carousel_slider: ^4.2.1
  
  # Story View = Instagram Stories UI
  # Stories anzeigen mit Timer und Tap-Steuerung
  story_view: ^0.16.0
  
  # Card Swiper = Tinder-Style Swipe
  # Für Dating-Feature (Swipe Left/Right)
  flutter_card_swiper: ^7.0.1
  
  # Color Picker = Farben auswählen
  # Für Video-Editing Features
  flutter_colorpicker: ^1.0.3
  
  # Slider Drawer = Seitliches Menü
  # Hamburger-Menu wie bei WeChat
  flutter_slider_drawer: ^2.1.1
  
  # ============================================
  # 🔔 SENSORS & HARDWARE (Geräte-Sensoren)
  # ============================================
  # Sensors Plus = Beschleunigungssensor
  # Für "Shake to find friends" Feature
  sensors_plus: ^7.0.0
  
  # ============================================
  # 📁 FILE HANDLING (Dateien)
  # ============================================
  # File Picker = Dateien auswählen
  # Dokumente, PDFs, etc. hochladen
  file_picker: ^6.1.1
  
  # MIME = Dateitypen erkennen
  # Ist das ein Bild? Video? PDF?
  mime: ^1.0.4
  
  # ============================================
  # 🌍 INTERNATIONALIZATION (Mehrsprachigkeit)
  # ============================================
  # Intl = Datumsformate, Zahlenformate
  # "vor 5 Minuten", "€10,99", etc.
  intl: ^0.19.0
  
  # ============================================
  # 🔒 PERMISSIONS (Berechtigungen)
  # ============================================
  # Permission Handler = Berechtigungen anfragen
  # "Darf die App auf Kamera zugreifen?"
  permission_handler: ^11.1.0
  
  # ============================================
  # 🤝 SOCIAL FEATURES (Teilen)
  # ============================================
  # Share Plus = Inhalte teilen
  # "Teile diesen Post auf WhatsApp"
  share_plus: ^7.2.1
  
  # ============================================
  # 🍎 iOS ICONS (Apple-Style Icons)
  # ============================================
  # Cupertino Icons = iOS-Style Icons
  # Für schöne iOS-Optik
  cupertino_icons: ^1.0.8

# ============================================
# 🧪 DEV DEPENDENCIES (Nur für Entwicklung)
# ============================================
dev_dependencies:
  # Flutter Test = Unit Tests schreiben
  flutter_test:
    sdk: flutter
  
  # Flutter Lints = Code-Qualität prüfen
  # Zeigt Warnungen bei schlechtem Code
  flutter_lints: ^5.0.0

# ============================================
# 🎨 FLUTTER CONFIGURATION
# ============================================
flutter:
  # Material Design Icons verwenden
  uses-material-design: true
  
  # Hier kommen später unsere Bilder, Fonts, etc.
  # assets:
  #   - assets/images/
  #   - assets/icons/
