// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWK4wkXt1eAFkFaND7vpJfI63esLAypKE',
    appId: '1:467507284871:web:5acde213cc7aec2c86a122',
    messagingSenderId: '467507284871',
    projectId: 'wechat-super-app-2024',
    authDomain: 'wechat-super-app-2024.firebaseapp.com',
    storageBucket: 'wechat-super-app-2024.firebasestorage.app',
    measurementId: 'G-5BG98ESG31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgWNxd4vXOcw3T47IVh5NCjZRS_ov46BI',
    appId: '1:467507284871:android:a075e6c46c191ad086a122',
    messagingSenderId: '467507284871',
    projectId: 'wechat-super-app-2024',
    storageBucket: 'wechat-super-app-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGVufF8GJwbnArC381syqomqt9IM9RDK0',
    appId: '1:467507284871:ios:6d75861935e52efb86a122',
    messagingSenderId: '467507284871',
    projectId: 'wechat-super-app-2024',
    storageBucket: 'wechat-super-app-2024.firebasestorage.app',
    iosClientId: '467507284871-jc2sc45tvk4qbi4qnkd51727h5urpfag.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechatCloneNew',
  );
}
